JizdniRad/JizdniRad/Models/Line.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace JizdniRad.Models;

[Table("Line")]
public partial class Line
{
    public int ID { get; set; }

    public DateTime ValidTo { get; set; }

    public string Name { get; set; }

    public string Zone { get; set; }

    public int? FirstStopID { get; set; }

    public virtual ICollection<Departure> Departures { get; set; } = new List<Departure>();

    [ForeignKey("ID")]
    public virtual LineStop? FirstStop { get; set; }
}

JizdniRad/JizdniRad/Controllers/LineController.cs
using JizdniRad.Context;
using JizdniRad.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace JizdniRad.Controllers
{
    public class LineController : Controller
    {

        private readonly DatabaseContext db;

        public LineController(DatabaseContext databaseContext)
        {
            db = databaseContext;

        }
        public IActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Detail(int id, int? stopIDfrom = null)
        {
            Line? line = db.lines.Include(x=>x.FirstStop).ThenInclude(x=>x.Stop).Where(x=>x.ID==id).FirstOrDefault();
            int offset = 0;
            LineStop? lineStopfrom = null;
            if (line==null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (stopIDfrom!=null)
            {
                lineStopfrom = db.lineStops.Where(x => x.LineID == id && x.ID == stopIDfrom).FirstOrDefault();
                if (lineStopfrom==null)
                {
                    return RedirectToAction("Detail",new {id=line.ID});
                }
                var current = db.lineStops.Where(x => x.ID == line.FirstStopID).FirstOrDefault();

                var linestopsLocal = db.lineStops.Where(x => x.LineID == line.ID).ToList();

                while (current.ID != lineStopfrom.ID)
                {
                    offset += current.TimeToNextStop ?? 0;
                    current = linestopsLocal.Where(x => x.ID == current.NextLineStopID).FirstOrDefault();

                    if (current == null)
                    {
                        break;
                    }
                    //Debug.WriteLine(current.ID);
                }
             
                this.ViewBag.offset = offset;
                this.ViewBag.from = lineStopfrom;
            }
            
            

            List<LineStop> stops = new List<LineStop>();
            stops.Add(db.lineStops.Include(x=>x.Stop).Include(x=>x.Line).Where(x => x.ID == line.FirstStopID).FirstOrDefault());

            List<LineStop> lineStopLocal = db.lineStops.Include(x=>x.Stop).Include(x=>x.Line).Where(x => x.LineID == line.ID).ToList();

            while (stops.Last().NextLineStopID!=null)
            {
                stops.Add(lineStopLocal.Where(x => x.ID == stops.Last().NextLineStopID).FirstOrDefault());
            }
            this.ViewBag.Stops = stops;


            var depratures = db.departures.Where(x => x.LineID == line.ID).ToList();
            foreach (var item in depratures)
            {
                item.Time += TimeSpan.FromMinutes(offset);
            }
            this.ViewBag.depratures = depratures;

            return View(line);  
        }
    }
}

JizdniRad/JizdniRad/ViewComponents/DepartureRowViewComponent.cs
using JizdniRad.Models;
using Microsoft.AspNetCore.Mvc;

namespace JizdniRad.ViewComponents
{
    public class DepartureRowViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke(List<Departure> departures)
        {
            return View(departures);
        }
    }
}

JizdniRad/JizdniRad/ViewComponents/SideDepartureViewComponent.cs
using JizdniRad.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace JizdniRad.ViewComponents
{
    
    public class SideDepartureViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke(List<LineStop> stops, Line line, LineStop from= null)
        {
            this.ViewBag.from = from;
            this.ViewBag.line = line;
            


            return View(stops);
        }
    }
}

JizdniRad/JizdniRad/Views/Line/Detail.cshtml
@using JizdniRad.Models
@model Line

<div class="container">

    <div class="row">
        <div class="col-1 border border-2 border-dark">
            <h1>@Model.Name</h1>
        </div>
        <div class="col-2 border border-2 border-dark">
            PID
        </div>
        <div class="col-8 container border border-2 border-dark">
            <div class="row">
                <p id="testsmall">PRAŽSKÁ INTEGROVANÁ DOPRAVA (PID) - Městská doprava Praha</p>
            </div>
            <div class="row">
                <p id="testsmall">Dopravce: Dopravní podnik hl. m. Prahy, akciová společnost,Sokolovská 42/217, Vysočany,190 00 Praha 9</p>
            </div>
            <div class="row">
                <p id="testsmall">Informace o provozu PID na tel.: 296 191 817; na internetu: www.dpp.cz</p>
            </div>

        </div>
        <div class="col-1 container border border-2 border-dark">

            <div class="row">
                Platnost:
            </div>
            <div class="row">
                od @Model.ValidTo.ToShortDateString()
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-3 border border-2 border-dark container">
            <div class="row">
                <div class="col-1">
                    <p id="testsmall">
                        orientační doba jízdy (min)
                    </p>

                </div>
                <div class="col-11">
                    <h4 class="text-end">Tarifní pásmo @Model.Zone</h4>
                </div>
            </div>
        </div>

        <div class="col-9 container border border-2 border-dark">
            <div class="row ">


                <div class="col-6 ">
                    <h5 class="text-center">PRACOVNÍ DEN (⚒)</h5>
                </div>
                <div class="col-3 ">
                    <h5 class="text-center"> SOBOTA (⑥)</h5>
                </div>
                <div class="col-3">
                    <h5 class="text-center">NEDĚLE (✝)</h5>
                </div>
            </div>
        </div>
    </div>

    <div class="row">

        <div class="col-3  container border border-2 border-dark">
            @if (this.ViewBag.from != null)
            {
                <vc:side-departure stops="@this.ViewBag.Stops" from="this.ViewBag.from" line="@Model"></vc:side-departure>
            }
            else
            {
                <vc:side-departure stops="@this.ViewBag.Stops" line="@Model"></vc:side-departure>
            }
        </div>
        <div class="col-9  container border border-2 border-dark">


            <vc:departure-row departures="@this.ViewBag.depratures"></vc:departure-row>


        </div>
    </div>





</div>